#!/usr/bin/python3
from sys import argv as args

if 'paste' in args or 'p' in args or 'P' in args or 'v' in args or 'V' in args:
    try:
       import clipboard
    except ImportError:
       print("please, install the package python3-pip or python-pip(on arch-linux)\nafter run \"sudo pip3 install clipboard\"")
       print("\nafter this doed, run this script again.")

    print(clipboard.paste().strip(), end='')
else:
    try:
       import clipboard
    except ImportError:
       print("please, install the package python3-pip or python-pip(on arch-linux)\nafter run \"sudo pip3 install clipboard\"")
       print("\nafter this doed, run this script again.")

    def read():
        from sys import stdin
        return stdin.read()

    if len(args)>2:
       clipboard.copy(' '.join(args[2:]))
       print("the text \"{}\" was copied!".format(' '.join(args[2:])))
    else:
       clipboard.copy(read())
       print("the text was copied")
