#!/usr/bin/python3
from sys import stdin, stderr, exit, argv as args

try:
    import clipboard
except ImportError:
    print("ERROR: please, install the \"clipboard\" library to continue.")
    exit(1)

if '-h' in args or '--help' in args:
    print('''
Usage: clip TEXT [-h] [paste]

A ultility for copy and paste using the terminal.

-h, --help      Show this message and exit
v, paste        Show the text from clipboard

Example:

echo "this text will be copied."| clip
clip "this text will be copied."
clip paste | grep 'text'
'''.strip())
    exit(0)

for arg in args[1:]:
    if arg not in ['v', 'paste', 'c', 'copy']:
        print('Usage: clip [-h] [paste|copy]')
        print('Clip: the "{}" arg is not valid!', file=stderr)
        exit(1)

if 'paste' in args or 'p' in args:
    print(clipboard.paste().strip(), end='')
else:
    def read():
        return stdin.read()

    if len(args) > 2:
        clipboard.copy(' '.join(args[2:]))
        print(' '.join(args[2:]), end='')
    else:
        text = read()
        clipboard.copy(text.strip())
        print(text, end='')
