#!/usr/bin/python3

from sys import argv as args

try:
   import clipboard
except ImportError:
   print("please, install the package python3-pip or python-pip(on arch-linux)\nafter run \"sudo pip3 install clipboard\"")
   print("\nafter this doed, run this script again.")

def read():

   text = ''
   try:
      while True:
         text += input()
         text += '\n'
   except EOFError:
      return text.strip()

if len(args)>1:
   clipboard.copy(' '.join(args[1:]))
   print("the text \"{}\" was copied!".format(' '.join(args[1:])))
else:
   clipboard.copy(read())
   print("the text was copied")
